feat: Implement SignIn Page
KWEBofficial/kubid-client pull request #2
Opened 2024-01-11 16:49 UTC by hyeok1235

- Implemented SignIn Page
- Refactored some of the SignUp Page

TODO: Fix antd: Message Error

2024-01-12 05:27 UTC, hypnotes requested changes
테스트는 해보지 못했습니다..ㅎ 몇가지 부탁드려용!

2024-01-12 05:27 UTC, hypnotes commented on src/components/common/MatchingPasswordInput.tsx
> +  const [passwordsMatch, setPasswordsMatch] = useState<boolean>(true);
boolean 값은 `is~`로 시작하면 좋습니다. 또한, 여기서 password들만 state값이니 굳이 state값 아니고 그냥 변수로 뺴도 괜찮을 것 같아요!

2024-01-12 05:27 UTC, hypnotes commented on src/components/signin/SignInLayout.tsx
> +      setIsSignInSuccessful(true);
오 이렇게 해야됐던 이유가 있었나요? 제가 물론 테스트는 못해봤지만 try문에서 catch문으로 넘어가지 않는다는 것은 postSignIn이 성공적이라서인걸로 알고 있는데...

2024-01-12 05:27 UTC, hypnotes commented on src/components/signin/SignInLayout.tsx
> +      {/* LargeInput for Email */}
jsx부분은 컴포넌트명으로 충분히 기능을 유추할 수 있으니 주석은 지워주셔도 될것 같아요! (JSX는 안그래도 복잡한데 더 복잡해지는지라..)

2024-01-12 05:27 UTC, hypnotes commented on src/pages/SignInPage.tsx
> +      <h2 style={{ margin: 24, textAlign: "center" }}>로그인</h2>
antd [Typography](https://ant.design/components/typography)를 적극적으로 사용해봅시다!

2024-01-12 10:05 UTC, hyeok1235 commented on src/components/common/MatchingPasswordInput.tsx
> +  const [passwordsMatch, setPasswordsMatch] = useState<boolean>(true);
passwordsMatch를 변수로 빼도 뒤에 나오는 p 태그에서 passwordsMatch 값을 쓸 수 있는 방법이 있을까요? 그냥 변수로 할 때 scope의 제한을 피하는 방법을 잘 모르겠습니다

2024-01-12 10:12 UTC, hyeok1235 commented on src/components/signin/SignInLayout.tsx
> +      setIsSignInSuccessful(true);
해당 파일에서 27-37번째 줄에서 setIsSignInSuccessful을 활용해서 message를 한번 더 보내는 프로세스가 있어서 try / catch 문 활용했습니다. 질문이 잘 이해가 안가는데 이걸 여쭤보신건가요?

2024-01-12 15:07 UTC, hypnotes commented on src/components/common/MatchingPasswordInput.tsx
> +  const [passwordsMatch, setPasswordsMatch] = useState<boolean>(true);
음 요거 그냥 그대로 쓰시면 될 것 같은데요?? `{!isPasswordMatch && <p>비밀번호가 일치하지 않습니다</p>}` 이런식? 혹시 제가 질문을 제대로 이해했을까요??

2024-01-12 15:09 UTC, hypnotes commented on src/components/signin/SignInLayout.tsx
> +      setIsSignInSuccessful(true);
아아 넵  setSignInSuccesful state값이랑 useEffect 사용 안하고 바로 띄울수는 없을까 해서 여쭤본거였어요! 코드 적을수록 좋긴 해서

2024-01-12 21:00 UTC, hyeok1235 commented on src/components/common/MatchingPasswordInput.tsx
> +  const [passwordsMatch, setPasswordsMatch] = useState<boolean>(true);
아 넵! `let isPasswordMatch = true;` 이렇게 그냥 변수로 선언해서 값 변경할 수 있게 했습니다!

2024-01-12 21:02 UTC, hyeok1235 commented on src/components/signin/SignInLayout.tsx
> +      setIsSignInSuccessful(true);
`setIsSignInSuccessful` 이 코드 자체가 성공하면 추가적으로 message를 보내는 것 같은데 꼭 필요한 것 같지는 않아서 일단 아예 삭제했습니다! 나중에 필요한 부분이면 다시 추가하도록 하겠습니당

2024-01-13 08:37 UTC, hypnotes approved these changes
다 고쳐진거면 일단 머지하시죠! auth kit 사용하는 부분은 다른 PR 에 해요~

2024-01-13 08:43 UTC, merged