Feature: 메인 페이지 draft
KWEBofficial/kubid-client pull request #3
Opened 2024-01-12 12:01 UTC by soonduck-dreams

![mainpage](https://github.com/KWEBofficial/kubid-client/assets/115782193/b4d18b9a-2e12-47ce-897d-eb5e5e656ffc)

## 작업 내용
- 메인 페이지 디자인 초안
- `GET /products`로 DB에서 상품 조회
- 각 아이템 버튼에 `products/{id}`로 가는 링크
- props 이용해 각 섹션의 최대 표시 아이템 개수 설정 가능 (사진은 예시로 각각 2, 4, 0으로 설정했습니다)
- 아이템이 없을 때 다른 문구 표시되도록 함 (임시)
## 이슈
- 각 섹션에 알맞은 API 개발이 필요할 것 같습니다~ 지금 섹션 구성이 확정된 건지는 모르겠지만 대강 예상해보면
  - 지금 핫한: `status`가 `progress`인 상품을 입찰자 많은 순서대로 정렬
  - 최근에 올라온: `status`가 `progress`인 상품을 최근 생성된 순서대로 정렬
  - {학과}에서 많이 보고 있어요: 음 잘 모르겠습니다
  - 어쨌든 현재 `GET /products`는 아무런 조건 없이 순수하게 가져오고 있어서, `status`가 `complete`인 것도 가져오고 있는 상태입니다
---
앞으로 계속 수정해야겠지만 일단 지금 정도에서 merge를 시키는 것도 나쁘지 않을 것 같아서 올려봅니닷

2024-01-12 12:03 UTC, soonduck-dreams commented
test

2024-01-12 12:07 UTC, soonduck-dreams commented
test

2024-01-12 12:09 UTC, soonduck-dreams commented
test

2024-01-12 12:10 UTC, soonduck-dreams reviewed
test

2024-01-12 12:15 UTC, soonduck-dreams commented
test

2024-01-12 12:19 UTC, soonduck-dreams commented
### 테스트용 더미 데이터
```
INSERT INTO product (product_name, `desc`, status, lower_bound, upper_bound, image_id, trading_place, trading_time, user_id, department_id)
VALUES
('Product 1', 'Description 1', 'progress', 1000, 30000, 1, 'Trading Place 1', 'Trading Time 1', 1, 1),
('Product 2', 'Description 2', 'complete', 5000, 20000, 2, 'Trading Place 2', 'Trading Time 2', 2, 2),
('Product 3', 'Description 3', 'progress', 8000, 25000, 3, 'Trading Place 3', 'Trading Time 3', 3, 3),
('Product 4', 'Description 4', 'complete', 3000, 15000, 4, 'Trading Place 4', 'Trading Time 4', 4, 4);

INSERT INTO bidding (price, user_id, product_id)
VALUES
(15000, 4, 1),
(18000, 3, 2),
(22000, 2, 3),
(12000, 1, 4);
```

2024-01-13 08:35 UTC, hypnotes requested changes

2024-01-13 09:17 UTC, soonduck-dreams commented on src/components/main_page/ItemList/ItemListBody.tsx
> +      <div css={BodyStyle}>
제가 [전에 피드백 받고](https://discordapp.com/channels/1189562991373471765/1194620075970412614/1194936982699262005) emotion을 사용해서 메인페이지는 다 이런 식으로 되어 있긴 한데... styled components로 통일하는 게 좋을까요?

2024-01-13 09:22 UTC, mobius29 commented on src/pages/mainpage/index.tsx
> +    }),
얘는 외부함수로 따로 분리 안해도 될 것 같아요!

2024-01-13 09:23 UTC, mobius29 commented on src/pages/mainpage/index.tsx
> +};
api 호출하는 부분만 분리하고, 나머지는 컴포넌트 안에 작성해줍시다!

2024-01-13 09:23 UTC, hypnotes commented on src/components/main_page/ItemList/ItemListBody.tsx
> +      <div css={BodyStyle}>
사실 잘 분리되어 있어서 상관은 없을듯 한데,  통일은 필욯ㄹ 것 같아용 오늘 회의에서 얘기해보시죠!

2024-01-13 10:10 UTC, soonduck-dreams commented on src/pages/mainpage/index.tsx
> +};
기존 코드 통째로 옮겨서 아래처럼 수정해 놓았습니다! api 호출하는 부분 분리는 `messageApi` 말씀하시는 건가용?
```
useEffect(() => {
    const fetchRecentProducts = async () => {
      try {
        const rawProducts = await getRecentProducts();
        ...
      } catch (error) {
        ...
      }
    };
    fetchRecentProducts();
}, []);
```

2024-01-13 10:22 UTC, soonduck-dreams commented on src/components/main_page/SearchSection/DepartmentDropdown.tsx
> +  <ConfigProvider
App.tsx에 넣으면 해당 사항들이 전역적으로 적용되어서 문제가 되지 않을까... 그래서 여기에 두었습니다
이 페이지에만 적용되게 하는 방법이 있을까요?

2024-01-13 10:37 UTC, soonduck-dreams commented
지금까지 올라온 피드백 반영했습니다~ 추가 피드백 편하게 말해주세요

2024-01-13 10:37 UTC, soonduck-dreams reviewed
지금까지 올라온 피드백 반영했습니다~ 추가 피드백 있으시면 편하게 말해주세요

2024-01-14 13:04 UTC, soonduck-dreams reviewed
![img](https://github.com/KWEBofficial/kubid-client/assets/115782193/f2f4ce4b-8858-4160-8280-48814aefd312)

[오늘 새로 만든 API](https://github.com/KWEBofficial/kubid-server/pull/30)를 적용했습니다.
이후 "지금 핫한"에 있는 걸 "OO학과에서 많이 찾는"에서 걸러주는 것을 구현할 예정입니다.

2024-01-15 13:27 UTC, mobius29 approved these changes

2024-01-15 14:44 UTC, merged